# Connectivity

## Universal Access

| Question                                                                                                                                                                                                          | Status                                    | Future |  Solution |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------|--------|:---------:|
| Does your country have a national broadband plan or policy to develop a high-speed access network?                                                                                                                | YES                                       |        |           |
| If yes, does the plan or policy include government investment in infrastructure to make broadband more broadly available?                                                                                         | YES                                       |        |           |
| If yes, what areas are the government investments targeting: Check all that apply.                                                                                                                                |                                           |        |           |
| - If yes, what areas are the government investments targeting: First mile                                                                                                                                         | YES                                       |        |           |
| - If yes, what areas are the government investments targeting: Middle mile                                                                                                                                        | YES                                       |        |           |
| - If yes, what areas are the government investments targeting: Last mile                                                                                                                                          | YES                                       |        |           |
| - If yes, what areas are the government investments targeting: Invisible mile                                                                                                                                     | YES                                       |        |           |
| If yes, does the plan or policy include blended finance or public-private partnership investment schemes for broadband expansion?                                                                                 | YES                                       |        |           |
| Does your country mandate the financing of a Universal Service Fund (USF) for services such as voice telephony services, fixed broadband Internet access services, and terrestrial mobile communication services? | YES                                       |        |           |
| Are fiscal incentives in place to accelerate internet deployment?                                                                                                                                                 | NO                                        |        |           |
| - If yes, specify: Accelerated depreciation for connectivity infrastructure investments:                                                                                                                          | NO                                        |        |           |
| - If yes, specify: Tax credits for research and development:                                                                                                                                                      | NO                                        |        |           |
| - If yes, specify: Loans, Guarantees or Subsidies for Connectivity Infrastructure:                                                                                                                                | NO                                        |        |           |
| Is equal access available to shared or government owned infrastructure such as road, railways, water and power lines?                                                                                             | NO                                        |        |           |
| Does the law in your country require its cable operators to provide open access for internet services?                                                                                                            | NO                                        |        |           |
| Does the law provide for unbundling and line sharing rules?                                                                                                                                                       | YES                                       |        |           |
| What restrictions, if any, are placed on foreign ownership of foreign telecom operators?                                                                                                                          | Minimum Level of Local Ownership Mandated |        |           |
| - If Other, Please Specify:                                                                                                                                                                                       | N/A                                       |        |           |
| Does your country’s national broadband plan or policy set a performance target for minimum download speed Mbps?                                                                                                   | NO                                        |        |           |
| Does your country’s national broadband plan or policy set coverage targets?                                                                                                                                       | NO                                        |        |           |
| - Population with Broadband                                                                                                                                                                                       | NO                                        |        |           |
| - Population with Broadband Target % of Population                                                                                                                                                                | N/A                                       |        |           |
| - Businesses with Broadband                                                                                                                                                                                       | NO                                        |        |           |
| - Businesses with Broadband Target % of Businesses                                                                                                                                                                | N/A                                       |        |           |
| - Schools with Broadband                                                                                                                                                                                          | NO                                        |        |           |
| - Schools with Broadband Target % of schools                                                                                                                                                                      | N/A                                       |        |           |
| - Rural Coverage                                                                                                                                                                                                  | NO                                        |        |           |
| - Rural Coverage Target % of rural population                                                                                                                                                                     | N/A                                       |        |           |
| - Population with mobile internet                                                                                                                                                                                 | NO                                        |        |           |
| - Population with mobile internet Target % of population                                                                                                                                                          | N/A                                       |        |           |
| - PC ownership                                                                                                                                                                                                    | NO                                        |        |           |
| - PC ownership Target % of population                                                                                                                                                                             | N/A                                       |        |           |
| - E-Government                                                                                                                                                                                                    | NO                                        |        |           |
| - E-Government. Please Specify                                                                                                                                                                                    | N/A                                       |        |           |
| - Other                                                                                                                                                                                                           | NO                                        |        |           |
| - Other. Please Specify                                                                                                                                                                                           | N/A                                       |        |           |
| Are fiscal incentives in place to increase access to broadband?                                                                                                                                                   | NO                                        |        |           |
| - If yes, do the fiscal incentives include device (computer or mobile) subsidies:                                                                                                                                 | NO                                        |        |           |
| - If yes, do the fiscal incentives include broadband service subsidies:                                                                                                                                           | NO                                        |        |           |
| - If yes, do the fiscal incentives include rural broadband subsidies:                                                                                                                                             | NO                                        |        |           |
| Does your country’s broadband plan or program include the rollout of free, public access points?                                                                                                                  | NO                                        |        |           |
| Can a broadband connection request be completed entirely online?                                                                                                                                                  | YES                                       |        |           |
| How much time is required to obtain internet connection service? (Calendar days)                                                                                                                                  | 5.5                                       |        |           |
| What is the average cost to request internet connection service? (USD)                                                                                                                                            | 500                                       |        |           |
| What is the average price for a month of business broadband connection with at least 10 Mbps download speed with unlimited data usage? (USD)                                                                      | 1000                                      |        |           |
| Are there fees or penalties for switching broadband providers?                                                                                                                                                    | YES                                       |        |           |


## Spectrum Management

| Question                                                                                                    | Status | Future |  Solution |
|-------------------------------------------------------------------------------------------------------------|--------|--------|:---------:|
| Does your country assign spectrum on the basis of competitive auctions?                                     | YES    |        |           |
| - If yes, please specify how the spectrum auction winners are primarily evaluated: Bid Price                | YES    |        |           |
| - If yes, please specify how the spectrum auction winners are primarily evaluated: Speed of Build-Out       | YES    |        |           |
| - If yes, please specify how the spectrum auction winners are primarily evaluated: Technology               | YES    |        |           |
| Does your country have policies and regulations that allow the following practices for spectrum allocation? |        |        |           |
| - Spectrum shortage evaluations:                                                                            | YES    |        |           |
| - Voluntary spectrum trading:                                                                               | NO     |        |           |
| - Voluntary spectrum leasing:                                                                               | NO     |        |           |
| - Spectrum caps:                                                                                            | NO     |        |           |
| - Secondary markets for unlicensed spectrum (TVWS or other relevant frequency bands)?                       | NO     |        |           |


## Obtaining & Protecting Domain Names

| Question                                                                                                                                                              	| Status 	| Future 	| Solution 	|
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------	|--------	|--------	|--------------------	|
| Which of the following are required to secure a country code top-level domain registration?                                                                           	|        	|        	|                    	|
| - Trademark matching the domain name:                                                                                                                                 	| NO     	|        	|                    	|
| - Legal name of entity:                                                                                                                                               	| YES    	|        	|                    	|
| - Local business registration:                                                                                                                                        	| YES    	|        	|                    	|
| - Local business address:                                                                                                                                             	| YES    	|        	|                    	|
| - Business owner must be a national or permanent resident:                                                                                                            	| NO     	|        	|                    	|
| Which of the following are considered legitimate reasons for denial of domain name registration? Check all that apply:                                                	|        	|        	|                    	|
| - Type of domain name (.edu, .org) do not match type of entity                                                                                                        	| NO     	|        	|                    	|
| - Attempt to divert consumers either for commercial gain or in an attempt to disrupt or disparage another entity                                                      	| YES    	|        	|                    	|
| - Financial gain without no intention to use the mark with the sale of goods or services (cyber-speculation)                                                          	| YES    	|        	|                    	|
| - Domain name holder has previously registered and sold domain names without intending to use them in connection with the sale of goods or services (cyber-squatting) 	| YES    	|        	|                    	|
| - Provision of false information when applying for registration of domain name                                                                                        	| YES    	|        	|                    	|
| Can a company transfer the domain name to a new registrant?                                                                                                           	| YES    	|        	|                    	|
| Are there laws or regulations on the following?                                                                                                                       	|        	|        	|                    	|
| - Bad Faith in user registration:                                                                                                                                     	| YES    	|        	|                    	|
| - Cyber-squatting:                                                                                                                                                    	| YES    	|        	|                    	|
| - Phishing, spam, or even distribution of malware:                                                                                                                    	| YES    	|        	|                    	|
| Is an authority or regulator outside of the courts responsible for domain name disputes or complaints?                                                                	| YES    	|        	|                    	|
| How much time is required to secure a domain name? (Calendar days)                                                                                                    	| 1      	|        	|                    	|
| What is the cost to request domain name registration service? USD                                                                                                     	| 12.5   	|        	|                    	|